image: python:3.7.8

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test

pylint:
  stage: Static Analysis
  script:
  - pylint -d C0301 project/*.py
  - pylint -d C0301 project/models/*.py
  - pylint -d C0301 project/views/*.py

pytest:
  stage: Test
  script:
  - cd project/test/;pytest -v
